site_name:     Guild AI
docs_dir:      .
site_dir:      ../build/docs
theme:         mkdocs
repo_url:      https://github.com/guildai/guild-client/
site_favicon:  favicon.ico
extra_css:     [guild.css]

markdown_extensions:
  - smarty

pages:
  - 'Home': index.md
  - 'Getting Started': getting-started.md
  - 'Tutorials':
      - 'Tutorials Overview': tutorials.md
      - 'Basic Neural Networks with MNIST': tutorial-mnist.md
      - 'Convolutional Neural Networks with CIFAR-10': tutorial-cifar10.md
      - 'Creating a Guild Project from Scratch': tutorial-project.md
      - 'Using Guild to publish benchmarks': tutorial-benchmarks.md
  - 'Docs':
      - 'Docs Overview': docs.md
      - 'User Guide': userguide.md
      - 'Command Reference': commandref.md
      - 'Project Reference': projectref.md
      - 'Developer Guide': devguide.md
  - 'FAQ': faq.md
  - 'About': about.md
